from django.urls import path
from django.conf.urls import url

from . import views
from . import api

urlpatterns = [
    path('', views.landing, name='landing'),
    path('templates', views.templates, name='templates'),
    path('email-lists', views.email_lists, name='email-lists'),
    path('edit-defaults', views.edit_defaults, name='edit-defaults'),
    path('edit-group-defaults', views.edit_group_defaults, name='edit-group-defaults'),
    path('edit-dimension-defaults', views.edit_dimension_defaults, name='edit-dimension-defaults'),
    path('edit-survey-defaults', views.edit_survey_defaults, name='edit-survey-defaults'),
    path('edit-question-defaults', views.edit_question_defaults, name='edit-question-defaults'),
    url(r'^add-survey/(?P<template>[0-9a-zA-Z\-_]+)/$', views.add_survey, name='add-survey'),
    url(r'^survey-confirm/(?P<id>[0-9a-zA-Z\-_]+)/$', views.survey_confirm, name='survey-confirm'),
    url(r'^add_groups/(?P<id>[0-9a-zA-Z\-_]+)/$', views.add_groups, name='add-groups'),
    url(r'^add_dimensions/(?P<id>[0-9a-zA-Z\-_]+)/$', views.add_dimensions, name='add-dimensions'),
    url(r'^add_questions/(?P<id>[0-9a-zA-Z\-_]+)/$', views.add_questions, name='add-questions'),
    url(r'^edit-survey/(?P<id>[0-9a-zA-Z\-_]+)/$', views.edit_survey, name='edit-survey'),
    url(r'^start-survey/(?P<id>[0-9a-zA-Z\-_]+)/$', views.start_survey, name='start-survey'),
    url(r'^survey-welcome/(?P<id>[0-9a-zA-Z\-_]+)/(?P<response_id>[0-9a-zA-Z\-_]+)/$', views.survey_welcome, name='survey-welcome'),
    url(r'^survey-close/(?P<id>[0-9a-zA-Z\-_]+)/(?P<response_id>[0-9a-zA-Z\-_]+)/$', views.survey_close, name='survey-close'),
    url(r'^group-select/(?P<id>[0-9a-zA-Z\-_]+)/(?P<response_id>[0-9a-zA-Z\-_]+)/$', views.group_select, name='group-select'),
    url(r'^take-survey/(?P<id>[0-9a-zA-Z\-_]+)/(?P<response_id>[0-9a-zA-Z\-_]+)/$', views.take_survey, name='take-survey'),
    url(r'^survey-report/(?P<id>[0-9a-zA-Z\-_]+)/$', views.survey_report, name='survey-report'),
    url(r'^survey-report-pdf/(?P<id>[0-9a-zA-Z\-_]+)/$', views.survey_report_pdf, name='survey-report-pdf'),
    url(r'^comparison-report/(?P<id>[0-9a-zA-Z\-_]+)/$', views.comparison_report, name='comparison-report'),
    url(r'^view-survey/(?P<id>[0-9a-zA-Z\-_]+)/$', views.view_survey, name='view-survey'),
    url(r'^email-lists/(?P<survey_id>[0-9a-zA-Z\-_]+)/$', views.email_lists, name='email-lists'),
    path('duplicate-survey', api.duplicate_survey, name='duplicate-survey'),
    path('toggle-survey', api.toggle_survey, name='toggle-survey'),
    path('toggle-session', api.toggle_session, name='toggle-session'),
    path('delete-survey', api.delete_survey, name='delete-survey'),
    path('edit-question', api.edit_question, name='edit-question'),
    path('delete-question', api.delete_question, name='delete-question'),
    path('add-group', api.add_group, name='add-group'),
    path('add-default-groups', api.add_default_groups, name='add-default-groups'),
    path('edit-group', api.edit_group, name='edit-group'),
    path('delete-group', api.delete_group, name='delete-group'),
    path('add-dimension', api.add_dimension, name='add-dimension'),
    path('add-default-dimension', api.add_default_dimensions, name='add-default-dimensions'),
    path('edit-dimension', api.edit_dimension, name='edit-dimension'),
    path('delete-dimension', api.delete_dimension, name='delete-dimension'),
    path('add-question', api.add_question, name='add-question'),
    path('add-default-questions', api.add_default_questions, name='add-default-questions'),
    path('edit-default-group', api.edit_default_group, name='edit-default-group'),
    path('delete-default-group', api.delete_default_group, name='delete-default-group'),
    path('edit-default-dimension', api.edit_default_dimension, name='edit-default-dimension'),
    path('delete-default-dimension', api.delete_default_dimension, name='delete-default-dimension'),
    path('edit-default-question', api.edit_default_question, name='edit-default-question'),
    path('delete-default-question', api.delete_default_question, name='delete-default-question'),
    path('survey-data', api.survey_data, name='survey-data'),
    path('delete-email', api.delete_email, name='delete-email'),
    path('edit-email', api.edit_email, name='edit-email'),
    path('add-email', api.add_email, name='add-email'),
    path('get-email-list', api.get_email_list, name='get-email-list'),
    path('add-email-list', api.add_email_list, name='add-email-list'),
    path('import-email-list', api.import_email_list, name='import-email-list'),
]