# Generated by Django 2.2.3 on 2019-07-30 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20190730_0429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Section',
            new_name='section',
        ),
    ]
