# Generated by Django 2.2.3 on 2019-07-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_answer_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
