# Generated by Django 2.2.4 on 2019-08-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_answer_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='closing_message',
            field=models.TextField(default='your done'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='description',
            field=models.TextField(default='a survey'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='group_message',
            field=models.TextField(default='which group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='name',
            field=models.CharField(default='survey1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='welcome_message',
            field=models.TextField(default='welcome'),
            preserve_default=False,
        ),
    ]
