# Generated by Django 2.2.4 on 2019-08-26 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_auto_20190826_0015'),
    ]

    atomic=False

    operations = [
        migrations.RenameModel(
            old_name='Section',
            new_name='Dimension',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='section',
            new_name='dimension',
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('questions', models.ManyToManyField(to='surveys.Question', verbose_name='Questions')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey', verbose_name='Survey')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
    ]
