# Generated by Django 2.2.4 on 2019-08-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_auto_20190826_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimension',
            name='description',
            field=models.TextField(default='a dimension', verbose_name='Description'),
            preserve_default=False,
        ),
    ]
