# Generated by Django 2.2.4 on 2019-08-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_dimension_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='groups',
            field=models.ManyToManyField(to='surveys.Group', verbose_name=''),
        ),
    ]
