# Generated by Django 2.2.4 on 2019-08-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_auto_20190828_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimension',
            name='color',
            field=models.CharField(max_length=12, null=True, verbose_name='Color'),
        ),
    ]
