# Generated by Django 2.2.4 on 2019-09-04 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_dimension_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.Group', verbose_name='Group'),
        ),
    ]
