# Generated by Django 2.2.4 on 2019-09-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_response_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_open',
            field=models.BooleanField(default=False, verbose_name='Survey Open'),
        ),
    ]
