# Generated by Django 2.2.4 on 2019-09-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0015_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='calculating',
            field=models.BooleanField(default=True, verbose_name='Calculating'),
        ),
    ]
