# Generated by Django 2.2.4 on 2019-09-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_question_calculating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='admin_email',
        ),
        migrations.AddField(
            model_name='survey',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Closed'),
        ),
    ]
