# Generated by Django 2.2.4 on 2019-09-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_auto_20190909_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='emails',
            field=models.TextField(default='', null=True, verbose_name='Emails'),
        ),
    ]
