# Generated by Django 2.2.4 on 2019-09-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0021_defaults_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaults',
            name='survey',
            field=models.TextField(default='{"description": "After identifying your participant group on the next screen, please rank this leader on a scale of 1-5 for each quality described. While we strongly encourage you to share your perspective in all areas, a \\"no response\\" option is provided for those who may not feel comfortable responding to a given item. ", "welcome": "Thank you for taking a few minutes to provide this leader with candid feedback regarding his/her job performance. Your responses will remain confidential and will be shared only as part of group information to help this leader learn more about perceptions of his/her work and in establishing performance goals. Your email address is requested for the sole purpose of survey management and will not be shared in any reports retained by the district. Please enter your email address, the passcode provided and click \'validate\' when you are ready to proceed. ", "closing": "You have completed the survey. Thank you again for your valued input which will be used to improve our organization. If you have additional insights or wish to provide feedback on the survey itself you are encouraged to contact your human resources office.  ", "closed_system": "Survey is offered to a minimum of seven predetermined participants for each group. Each will be forward a discreet password for access. Dimensions: As stated, please use definitions of dimensions included in the report to better define the standard dimensions. ", "group": "To which group do you belong?"}', verbose_name='Survey'),
        ),
    ]
