# Generated by Django 2.2.4 on 2019-09-12 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0023_survey_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Taken'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
