# Generated by Django 2.2.5 on 2019-09-25 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0024_auto_20190912_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantkey',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.Response', verbose_name='Response'),
        ),
    ]
