# Generated by Django 2.2.5 on 2019-09-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0026_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='current',
            field=models.BooleanField(default=True, verbose_name='Current'),
        ),
    ]
