# Generated by Django 2.2.5 on 2019-09-25 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0027_session_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='surveys.Session', verbose_name='Session'),
            preserve_default=False,
        ),
    ]
