# Generated by Django 2.2.5 on 2019-09-26 04:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0028_response_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date_ended',
            field=models.DateTimeField(null=True, verbose_name='Date Ended'),
        ),
        migrations.AddField(
            model_name='session',
            name='date_started',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Started'),
            preserve_default=False,
        ),
    ]
