# Generated by Django 2.2.5 on 2019-10-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0029_auto_20190926_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='value',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
