# Generated by Django 2.2.5 on 2019-10-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0030_auto_20191001_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='email_required',
            field=models.BooleanField(default=True, verbose_name='Email Required'),
        ),
    ]
