# Generated by Django 2.2.5 on 2019-10-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0032_auto_20191015_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimension',
            name='icon',
            field=models.ImageField(null=True, upload_to='icons', verbose_name='Icon'),
        ),
    ]
