# Generated by Django 2.2.6 on 2019-10-24 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0034_auto_20191022_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='free_use',
            new_name='public_use',
        ),
    ]
