# Generated by Django 2.2.6 on 2019-10-28 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0035_auto_20191024_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'EmailList',
                'verbose_name_plural': 'EmailLists',
            },
        ),
        migrations.AlterField(
            model_name='survey',
            name='public_use',
            field=models.BooleanField(blank=True, null=True, verbose_name='Public Use'),
        ),
        migrations.CreateModel(
            name='EmailListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('email_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.EmailList', verbose_name='List')),
            ],
            options={
                'verbose_name': 'EmailListing',
                'verbose_name_plural': 'EmailListings',
            },
        ),
    ]
