# Generated by Django 2.2.6 on 2019-10-28 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0037_remove_group_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='emails',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='surveys.EmailList', verbose_name='Emails'),
            preserve_default=False,
        ),
    ]
