# Generated by Django 2.2.6 on 2019-11-18 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0041_auto_20191118_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantkey',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='participantkey',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.Group', verbose_name='Group'),
        ),
    ]
