# Generated by Django 2.2.6 on 2019-11-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0042_auto_20191118_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='admin_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Admin Email'),
        ),
    ]
