# Generated by Django 2.2.4 on 2019-09-06 10:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0003_auto_20190730_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='rid')),
            ],
            options={
                'verbose_name': 'RegistrationRequest',
                'verbose_name_plural': 'RegistrationRequests',
            },
        ),
    ]
