# Generated by Django 2.2.4 on 2019-09-12 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userManagement', '0004_registrationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='Logo')),
                ('size', models.IntegerField(verbose_name='Font Size')),
                ('color', models.CharField(max_length=8, verbose_name='Text Color')),
                ('background', models.CharField(max_length=8, verbose_name='Background Color')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'HeaderSettings',
                'verbose_name_plural': 'HeaderSettingss',
            },
        ),
    ]
