# Generated by Django 2.2.4 on 2019-09-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0006_auto_20190912_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headersettings',
            name='logo',
            field=models.ImageField(default='default_logo.png', upload_to='logos/', verbose_name='Logo'),
        ),
    ]
