# Generated by Django 2.2.4 on 2019-09-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0007_auto_20190912_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headersettings',
            name='background',
            field=models.CharField(default='000000', max_length=8, verbose_name='Background Color'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='color',
            field=models.CharField(default='C2EFF0', max_length=8, verbose_name='Text Color'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='size',
            field=models.IntegerField(default=32, verbose_name='Font Size'),
        ),
    ]
