# Generated by Django 2.2.6 on 2019-10-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0010_passwordresetrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('category', models.CharField(choices=[('report', 'Report'), ('email', 'email')], max_length=50, verbose_name='Category')),
                ('content', models.TextField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settingss',
            },
        ),
    ]
