# Generated by Django 2.2.6 on 2019-10-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0011_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='list_setting',
            field=models.BooleanField(default=False, verbose_name='List Setting'),
        ),
    ]
