# Generated by Django 2.2.6 on 2019-10-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0012_settings_list_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='category',
            field=models.CharField(choices=[('report', 'Report'), ('email', 'Email')], max_length=50, verbose_name='Category'),
        ),
    ]
